### ==========================================================================
### CONFIGURATION
### ==========================================================================
@baseUrl = http://localhost:3000
@contentType = application/json
@userId = 892ac592-b017-4660-be6f-4dd881dfb0fe

### ==========================================================================
### AUTH MODULE
### ==========================================================================

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "johndoe@example.com",
  "password": "SuperSecret123!"
}

###
@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}

### Refresh Token
# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}

###
@newAccessToken = {{refresh.response.body.accessToken}}
@newRefreshToken = {{refresh.response.body.refreshToken}}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}

### Revoke User Sessions
DELETE {{baseUrl}}/auth/{{userId}}/sessions
Authorization: Bearer {{accessToken}}

### ==========================================================================
### DEPARTMENTS MODULE
### ==========================================================================

### Get All Departments
GET {{baseUrl}}/departments
Authorization: Bearer {{accessToken}}

### Create Department
POST {{baseUrl}}/departments
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "name": "Engineering",
  "code": "ENG"
}

### ==========================================================================
### USERS MODULE
### ==========================================================================

### Create User
POST {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "passwordPlainText": "SuperSecret123!",
  "role": "HR"
}

### Get All Users
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

### Activate User
PATCH {{baseUrl}}/users/{{userId}}/activate
Authorization: Bearer {{accessToken}}

### Deactivate User
PATCH {{baseUrl}}/users/{{userId}}/deactivate
Authorization: Bearer {{accessToken}}

### Change User Role
PATCH {{baseUrl}}/users/{{userId}}/role
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "role": "ROOT"
}