# ==========================================
# Build Image
# ==========================================
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ==========================================
# Production Runtime
# ==========================================
FROM node:22-alpine AS runner

ENV NODE_ENV=production
ENV PORT=3000

USER node

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --chown=node:node --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main"]